id: A715AB654
title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
type: translation
pechas:
- I6FBDB41B
- I08C08579
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:58:05.316842
  last_modified_at: 2023-01-04 12:58:05.316860
  collections:
  - Lochen Chönyi Zangmo
  - Works of Tibetan Masters
alignment_to_base:
  I6FBDB41B/7F3A: 4C0A
  I08C08579/AFF9: 4C0A
